name: CI/CD Pipeline - Build and Deploy to Staging

on:
  push:
    branches:
      - main
    # tags:
    #   - '*'

jobs:
  build:
    name: Build node js project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      # - name: Build Node App
      #   run: npm run build
      
      - name: Run Tests
        run: npm test

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shopeasy-node-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/shopeasy-node-app:latest

  deploy:
    name: Deploy to Remote VPS
    runs-on: self-hosted
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Docker login
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/shopeasy-node-app:latest

      - name: Stop old container
        run: |
          docker stop shopeasy-node-app || true && docker rm shopeasy-node-app || true

      - name: Run new container
        run: |
          docker run -d --name shopeasy-node-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/shopeasy-node-app:latest

  